name: CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: deploy to s3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_EC2_HOST }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_EC2_USER }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_EC2_KEY }}
          AWS_REGION: 'ap-northeast-2'
          SOURCE_DIR: 'dist'