name: React Vite CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install  

      - name: Build with Vite
        run: |
          npm run build  

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: app
          path: dist/

      - name: Set up SSH key
        run: |
          echo "${{ secrets.AWS_EC2_KEY }}" > private_key.pem  
          chmod 600 private_key.pem

      - name: Create app directory on EC2
        run: |
          ssh -i private_key.pem -t \
            -o StrictHostKeyChecking=no \
            ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }} << EOF
            mkdir -p /home/${{ secrets.AWS_EC2_USER }}/app
          EOF

      - name: Install pm2 on EC2 (optional)
        run: |
          ssh -i private_key.pem -t \
            -o StrictHostKeyChecking=no \
            ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }} << EOF
            npm install -g pm2
          EOF

      - name: Copy entire project to EC2
        run: |
          scp -i private_key.pem -o StrictHostKeyChecking=no -r * \
            ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }}:/home/${{ secrets.AWS_EC2_USER }}/app

      - name: Install dependencies on EC2
        run: |
          ssh -i private_key.pem -t \
            -o StrictHostKeyChecking=no \
            ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }} << EOF
            cd /home/${{ secrets.AWS_EC2_USER }}/app
            npm install
          EOF

      - name: Start development server on EC2
        run: |
          ssh -i private_key.pem -t \
            -o StrictHostKeyChecking=no \
            ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }} << EOF
            cd /home/${{ secrets.AWS_EC2_USER }}/app
            npm run dev -- --host
          EOF

      - name: Clean up SSH key
        run: rm -f private_key.pem
